# Generated by Django 4.1.3 on 2022-11-24 06:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolistitem',
            name='date',
            field=models.CharField(default='demotest@gmail.com', max_length=100),
            preserve_default=False,
        ),
    ]
