# Generated by Django 4.1.3 on 2022-11-29 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todolistitem_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolistitem',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
